apiVersion: v1
kind: Secret
metadata:
  name: root-secret #This is the root password, doesn't need change anything, but rememeber the password for the root password (Just in Case)
  namespace: changeme-pre #NAMESPACE
type: kubernetes.io/base64
data:
  root-password: cjk5cHczc3RlcmQxZ2l0YWw=
---
apiVersion: v1
kind: Secret
metadata:
  name: phpmyadmin-secret #This password uses in the phphmyadmin's pod, must be the same for the database's user in the docker file environment variable
  namespace: changeme-pre #NAMESPACE
type: kubernetes.io/base64
data:
  phppmyadmin-password: cHNzd3JkLXAxZjBkc2QtdXNlciE=
---
apiVersion: v1
kind: Secret
metadata:
  name: proyecto-secret #This password uses in the proyecto's pod, must be the same for the database's user in the docker file environment variable
  namespace: changeme-pre #NAMESPACE
type: kubernetes.io/base64
data:
  proyecto-password: cHNzd3JkLXAxZjBkc2QtdXNlciE=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-changeme #Name for mysql service must be the same here and in the SVC
  nnamespace: changeme-pre #NAMESPACE
spec:
  serviceName: "mysql-changeme" #Name for mysql service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-changeme #Name for mysql service
  template:
    metadata:
      labels:
        app: mysql-changeme  #Name for mysql service
    spec:
      containers:
        - name: mysql-changeme  #Name for mysql service
          image: mysql:8.1  #Docker Image
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-secret 
                  key: root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: changeme-mysql-pvc # REFERENCE: PVC NAME in storage yaml
              mountPath: /var/lib/mysql
            - name: changeme-mysql-scripts  #Reference NAME = 1
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: changeme-mysql-pvc # REFERENCE: PVC NAME in storage yaml
          persistentVolumeClaim:
            claimName: changeme-mysql-pvc # REFERENCE: PVC NAME in storage yaml
        - name: changeme-mysql-scripts  #Reference NAME = 1
          configMap:
            name: import-changeme-scripts  #REFERENCE: Is the name from the script in the configmap
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-changeme #Name for mysql service must be the same here and in the mysql deployment
  namespace: changeme-pre #NAMESPACE
spec:
  selector:
    app: mysql-changeme #Name for mysql service
  type: ClusterIP
  ports:
    - name: mysql-changeme #Name for mysql service
      port: 3306
      targetPort: 3306
